my-config:
  eureka:
    instance:
      hostname: 127.0.0.1
      heartbeatInterval: 2
      deadInterval: 6
    server:
      refreshInterval: 5
    client:
      fetchRegistryInterval: 5
  redis:
    host: 192.168.xxx.xxx
    port: 16379
    password: williamworkstation
  mysql:
    host: 192.168.xxx.xxx
    port: 3306
    db-name: web_message_center
    username: root
    password: 123456
  server:
    port: 8007
  swagger:
    enabled: true
  logging:
    config:
      root-path: /code/data/logs

